# the name of your track or event
name = "PL Summit"

# the name of the group organizing the event
org = "Protocol Labs"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "Juan Benet"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = ""

# the start date of the event
date = "2022-10-24"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "11:00 - 19:00 Local time"

# the event venue name (will show up on the event card - TODO)
venueName = "[Convento do Beato](https://goo.gl/maps/2yDdwVSHfgs1mYhL7)"

# the event venue address (will show up on a map -- TODO)
venueAddress = "Alameda do Beato 40, 1950-042 Lisboa, Portugal"

# the max number of attendees of the event
attendees = ""

# event registration - open or private
eventRegistration = "open"

# these is unsued:
# tickets = "Waitlist"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Conference"]

# a color, to group key events visually. use sparingly
color="orange"

# the position in the schedule table, leave blank if you don't need to control this
# "top" or "bottom"
position = "top"

# a description of the event.
# will show up when the user clicks the event card.
description = ""
